external_data_config:
  external_data_csv: data/external/Iris.csv

raw_data_config: 
  raw_data_csv: data/raw/train.csv
  model_var: ['Species','SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
  train_test_split_ratio: 0.3
  target: Species 
  random_state: 111
  new_train_data_csv: data/raw/new_train.csv

processed_data_config:
  train_data_csv: data/processed/iris_train.csv
  test_data_csv:  data/processed/iris_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: random_forest
  registered_model_name: random_forest_model
  remote_server_uri: http://localhost:1234

model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: Species
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html